# Generated by Django 5.0.5 on 2024-05-14 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDo_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasos',
            name='orden',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tareas',
            name='fechaCreacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 14, 1, 46, 13, 863471)),
        ),
        migrations.AddField(
            model_name='tareas',
            name='fechaFinalizacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 13, 1, 46, 13, 863471)),
        ),
    ]
